quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc=false

quarkus.datasource.flyway.db-kind=postgresql
quarkus.datasource.flyway.reactive=false
quarkus.datasource.flyway.jdbc.transactions=disabled

quarkus.flyway.flyway.migrate-at-start=true
quarkus.hibernate-orm.blocking=false
quarkus.hibernate-orm.schema-management.strategy=validate
