package com.alexastudillo.partyregistry.application.model;

/**
 * Enumerates the bounded application and transaction operations exposed to telemetry.
 */
public enum ObservedOperation {
    APPLICATION_NATURAL_PERSON_REGISTRATION,
    APPLICATION_LEGAL_ENTITY_REGISTRATION,
    APPLICATION_ADDITIONAL_IDENTIFIER_REGISTRATION,
    APPLICATION_PARTY_LIST,
    APPLICATION_PARTY_RETRIEVAL,
    APPLICATION_PARTY_PATCH,
    APPLICATION_PARTY_ACTIVATION,
    APPLICATION_PARTY_DEACTIVATION,
    APPLICATION_PARTY_ARCHIVAL,
    TRANSACTION_NATURAL_PERSON_REGISTRATION,
    TRANSACTION_LEGAL_ENTITY_REGISTRATION,
    TRANSACTION_ADDITIONAL_IDENTIFIER_REGISTRATION,
    TRANSACTION_PARTY_ACTIVATION,
    TRANSACTION_PARTY_MUTATION
}
