INSERT INTO identifier_schemes (
    id,
    code,
    issuing_country_code,
    category,
    applicable_subject_type,
    name,
    description,
    normalizer_key,
    validator_key,
    minimum_length,
    maximum_length,
    requires_expiration,
    status,
    created_by,
    updated_by,
    version
) VALUES
    (
        '0198d111-08f1-7e48-b291-399bbb9cd601',
        'TEST_NATURAL_ACTIVE',
        'EC',
        'NATIONAL_ID',
        'NATURAL_PERSON',
        'Test natural-person identifier',
        'Active test-only scheme for natural persons.',
        'TRIM_UPPERCASE_V1',
        'ALPHANUMERIC_V1',
        6,
        20,
        false,
        'ACTIVE',
        'test-fixture',
        'test-fixture',
        0
    ),
    (
        '0198d111-08f1-7e48-b291-399bbb9cd602',
        'TEST_LEGAL_ACTIVE',
        'EC',
        'LEGAL_REGISTRATION_NUMBER',
        'LEGAL_ENTITY',
        'Test legal-entity identifier',
        'Active test-only scheme for legal entities.',
        'TRIM_UPPERCASE_V1',
        'ALPHANUMERIC_V1',
        6,
        24,
        false,
        'ACTIVE',
        'test-fixture',
        'test-fixture',
        0
    ),
    (
        '0198d111-08f1-7e48-b291-399bbb9cd603',
        'TEST_BOTH_EXPIRING',
        'EC',
        'PASSPORT',
        'BOTH',
        'Test expiring identifier',
        'Active test-only scheme requiring expiration.',
        'TRIM_UPPERCASE_V1',
        'ALPHANUMERIC_V1',
        6,
        16,
        true,
        'ACTIVE',
        'test-fixture',
        'test-fixture',
        0
    ),
    (
        '0198d111-08f1-7e48-b291-399bbb9cd604',
        'TEST_BOTH_DRAFT',
        'EC',
        'OTHER',
        'BOTH',
        'Test draft identifier',
        'Inactive test-only draft scheme.',
        'TRIM_UPPERCASE_V1',
        'ALPHANUMERIC_V1',
        1,
        32,
        false,
        'DRAFT',
        'test-fixture',
        'test-fixture',
        0
    ),
    (
        '0198d111-08f1-7e48-b291-399bbb9cd605',
        'TEST_BOTH_DEPRECATED',
        'EC',
        'OTHER',
        'BOTH',
        'Test deprecated identifier',
        'Inactive test-only deprecated scheme.',
        'TRIM_UPPERCASE_V1',
        'ALPHANUMERIC_V1',
        1,
        32,
        false,
        'DEPRECATED',
        'test-fixture',
        'test-fixture',
        0
    ),
    (
        '0198d111-08f1-7e48-b291-399bbb9cd606',
        'TEST_BOTH_RETIRED',
        'EC',
        'OTHER',
        'BOTH',
        'Test retired identifier',
        'Inactive test-only retired scheme.',
        'TRIM_UPPERCASE_V1',
        'ALPHANUMERIC_V1',
        1,
        32,
        false,
        'RETIRED',
        'test-fixture',
        'test-fixture',
        0
    );
