package com.alexastudillo.partyregistry.domain.error;

/**
 * Identifies a transport-neutral violation of a Party Registry domain invariant.
 */
public enum DomainViolation {
    PARTY_ID_REQUIRED,
    TENANT_ID_REQUIRED,
    PARTY_STATUS_REQUIRED,
    PARTY_VERSION_REQUIRED,
    PARTY_VERSION_NEGATIVE,
    PARTY_VERSION_OVERFLOW,
    AUDIT_REQUIRED,
    AUDIT_TIMESTAMP_REQUIRED,
    AUDIT_TIMESTAMP_ORDER,
    AUDIT_USER_REQUIRED,
    AUDIT_USER_TOO_LONG,
    AUDIT_USER_UNSAFE,
    NATURAL_PERSON_DETAILS_REQUIRED,
    EVALUATION_DATE_REQUIRED,
    DISPLAY_NAME_REQUIRED,
    DISPLAY_NAME_TOO_LONG,
    GIVEN_NAMES_REQUIRED,
    GIVEN_NAMES_TOO_LONG,
    FAMILY_NAMES_REQUIRED,
    FAMILY_NAMES_TOO_LONG,
    PREFERRED_NAME_TOO_LONG,
    BIRTH_COUNTRY_CODE_INVALID,
    BIRTH_DATE_IN_FUTURE,
    DATE_OF_DEATH_IN_FUTURE,
    DEATH_BEFORE_BIRTH,
    PATCH_REQUIRED,
    EMPTY_PATCH
}
