-- Passport limits are a permissive admission policy, not an official numbering specification.
INSERT INTO identifier_schemes (
    code,
    issuing_country_code,
    category,
    applicable_subject_type,
    name,
    description,
    normalizer_key,
    validator_key,
    minimum_length,
    maximum_length,
    requires_expiration,
    status,
    created_at,
    created_by,
    updated_at,
    updated_by,
    version
)
VALUES
(
    'EC_NATIONAL_ID',
    'EC',
    'NATIONAL_ID',
    'NATURAL_PERSON',
    'Ecuadorian National Identity Card',
    'National identity document issued by Ecuador''s Civil Registry to individuals.',
    'TRIM_UPPERCASE_V1',
    'EC_NATIONAL_ID_V1',
    10,
    10,
    true,
    'ACTIVE',
    now(),
    'system',
    now(),
    'system',
    0
),
(
    'EC_TAX_ID',
    'EC',
    'TAX_ID',
    'BOTH',
    'Ecuadorian Taxpayer Identification Number',
    'Taxpayer registration number issued by Ecuador''s Internal Revenue Service (SRI).',
    'TRIM_UPPERCASE_V1',
    'EC_TAX_ID_V1',
    13,
    13,
    false,
    'ACTIVE',
    now(),
    'system',
    now(),
    'system',
    0
),
(
    'EC_PASSPORT',
    'EC',
    'PASSPORT',
    'NATURAL_PERSON',
    'Ecuadorian Passport',
    'Travel document issued by Ecuador to its citizens. Registration validates structure only, not issuance or ownership.',
    'TRIM_UPPERCASE_V1',
    'ALPHANUMERIC_V1',
    1,
    256,
    true,
    'ACTIVE',
    now(),
    'system',
    now(),
    'system',
    0
);
